Fixed hand posing when using custom mesh
oculus-samples/Unreal-HandGameplay pull request #11
Opened 2023-02-15 02:55 UTC by intvoker

2023-02-22 00:11 UTC, jasonmeisel requested changes
This seems like a great fix!

We suggest you change `bCustomHandMesh` to `bCustomPoseableHandMesh`, so that it isn't confused with the private field of the base class.

Thanks for the contribution!

2023-02-22 00:11 UTC, jasonmeisel commented on Plugins/OculusHandTools/Source/OculusHandPoseRecognition/Private/PoseableHandComponent.cpp
> +		bCustomHandMesh = true;
```suggestion
		bCustomPoseableHandMesh = true;
```

2023-02-22 00:11 UTC, jasonmeisel commented on Plugins/OculusHandTools/Source/OculusHandPoseRecognition/Private/PoseableHandComponent.cpp
> +	if (bCustomHandMesh && BoneNameMappings.Contains(Bone))
```suggestion
	if (bCustomPoseableHandMesh && BoneNameMappings.Contains(Bone))
```

2023-02-22 00:11 UTC, jasonmeisel commented on Plugins/OculusHandTools/Source/OculusHandPoseRecognition/Private/PoseableHandComponent.cpp
> +		const auto MappedBoneIndex = SkeletalMesh->GetRefSkeleton().FindBoneIndex(BoneNameMappings[Bone]);
```suggestion
		auto const MappedBoneIndex = SkeletalMesh->GetRefSkeleton().FindBoneIndex(BoneNameMappings[Bone]);
```

2023-02-22 00:11 UTC, jasonmeisel commented on Plugins/OculusHandTools/Source/OculusHandPoseRecognition/Public/PoseableHandComponent.h
> +	bool bCustomHandMesh = false;
```suggestion
	bool bCustomPoseableHandMesh = false;
```

2023-02-24 07:07 UTC, intvoker commented
@jasonmeisel, fixed!

2023-03-09 19:22 UTC, AlexThiv approved these changes

2023-03-09 22:26 UTC, merged